authors:
  nisarahamed:
    name: Nisar Ahamed
    description: AI Engineer
    avatar: https://avatars.githubusercontent.com/u/34709402?s=400&u=93706427f5441fa0d10086a0bc1b6298b06534df&v=4
    url: https://www.linkedin.com/in/nisarahamedk/